In [1]:
import os
os.chdir('/home/smallyan/eval_agent')
print(f"Working directory: {os.getcwd()}")

Working directory: /home/smallyan/eval_agent


In [2]:
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU device: {torch.cuda.get_device_name(0)}")
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(f"Using device: {device}")

CUDA available: True
GPU device: NVIDIA H100 NVL
Using device: cuda


# Consistency Evaluation — Binary Checklist

This notebook evaluates whether the research project meets its stated goals by checking:
- **CS1**: Conclusions vs Original Results
- **CS2**: Implementation Follows the Plan

Target repository: `/net/scratch2/smallyan/function_vectors_eval`

In [3]:
# Explore the repository structure
repo_path = "/net/scratch2/smallyan/function_vectors_eval"

for root, dirs, files in os.walk(repo_path):
    level = root.replace(repo_path, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 2 * (level + 1)
    for file in files:
        print(f'{subindent}{file}')

function_vectors_eval/
  .gitignore
  fv_overview.png
  documentation.pdf
  plan.md
  CodeWalkthrough.md
  fv_environment.yml
  src/
    portability_eval.py
    test_numheads.py
    compute_indirect_effect.py
    vocab_reconstruction.py
    __init__.py
    compute_avg_hidden_state.py
    natural_text_eval.py
    evaluate_function_vector.py
    compute_average_activations.py
    __pycache__/
      evaluate_function_vector.cpython-311.pyc
      __init__.cpython-311.pyc
      compute_indirect_effect.cpython-311.pyc
    utils/
      eval_utils.py
      prompt_utils.py
      intervention_utils.py
      extract_utils.py
      __init__.py
      model_utils.py
      __pycache__/
        model_utils.cpython-311.pyc
        intervention_utils.cpython-311.pyc
        __init__.cpython-311.pyc
        prompt_utils.cpython-311.pyc
        extract_utils.cpython-311.pyc
        eval_utils.cpython-311.pyc
    eval_scripts/
      eval_fv.sh
      eval_numheads.sh
      eval_template_portability.sh
     

      5b/
        374a492f210aa3508eaa2a595e0d6f62e3b777
        290b0d37441437c8e7f4a24e54e0b3dee809cb
        a93268f3c0605a4e6583a84291fa17a4f935f7
      e3/
        565db1142a8706c14d5889263d35df6caa3176
        8434095e71245260807e60d7609cdd67ae670d
        3130a7a2d49efdba4782d3b4ddaefba7f8c485
      8d/
        d92dadf8add5418c2d5fd224b8ee652e23de81
        59c04d5bc62a0bdbb4a85d8269ac6967a7c674
      36/
        7b0e2305e5b8797851379f1d7899613cf86445
      e4/
        e96b2f03a1971cc071645d2c37426fda0f8893
        c0afc33d42bada5ddcea8f10413ee2d43675a2
      b3/
        38eec1eadb22b554b9a1d2501816971b33b491
      8c/
        a0fe5354ae2dcd1d70197c859ca3c0d04e87c5
      74/
        68386814abb567c50590f868f5d7a2af0ca61b
      03/
        c1ec356a73e90f78b195be12a040a9003aa134
        3d23550fc9dbd0e9d48d2acc8d1f9b30c5f473
        c967514093be7b79e86aa9cc7598e589ef80b8
      90/
        1ede638124331fe219c6e9f27fdd54546e5545
        39a394cb587a280ea8a1e7f08f655925c6951d
       

      1c/
        dc7da06b34049700cafde7dc9688cc8afd72c8
        9da0b62fbdcb4af41979b9f8ceca6b1660fe0e
      45/
        b566d3780fd9483b6bd881d503de0b3b3b6351
        5c1ed62b2bb514483e02d7285adafc351dd4df
        44271d3aa54724fec967f2d63721bb12cdc6ad
      32/
        d2ea85bf76b335420151b4c8fec1d3dd9f7c43
      b0/
        7c904ad259e0246e8a6e3b2d4ca265aa9c9253
      e7/
        30084a611fa40d82149a4e91f5c05616d13ecd
      2a/
        7b964203513c9f915487be35adf8c866744652
      5f/
        bea705027ba16dfbcb9f6a8d3f6500ccf75ecd
        5987b2a2ac4a28b6e3edd9af92e377c83d787f
        4ba5262861061a88f38d2717b1bc900afe6adb
      dd/
        ab9c57100eb59f89933050bd062ed16fd4c8fa
        72c857212bfbca27bdde248d18d549f64cce10
        933ccd0a26a2255e46704c61100a70bdf045bb
      f5/
        84b9dd45829fbaaeb4facc1471bdb5d7e3297f
      99/
        2a57a357ae75f92416d057477852fc685a52aa
        3a48a1fa7e7dc1b4d20930edc4bf79a392d003
      c3/
        e18301583ff25160009488b10e6c7b7a01e3

      78/
        89c2dbd69ea9d90f35483f0aa5f47d1b2be18c
        bdb2b7c261029e5035f9c12a8e7d63a44e50cc
      5c/
        de25272ea93ca80c76cbee02e9b6477fb05258
        fa115e04c836ad2a59157016d98556b5e95cc4
      2d/
        d3d65ef181087322b1ff9c2f6b566dfa55af37
        026318c1610110f3aa2e012c05b16046f73e47
        46ec792061db563402b2eda040698f6f0cbfb6
        b9eca4385937eea26f413d6ade72fac335e068
      da/
        f0e80ad5682ba12e6409da3f2470713be929ab
      05/
        1d5b41a55813c4dc55dbc885a112e2e666f4c7
      6a/
        404746f5c3f625399ae655e280215c9a227cb2
      8e/
        729ace7148b677f4bc1925bbd6a07b52af50e8
      40/
        149e06c2df0092747e8ab3d53f6cf129087ac4
      e2/
        db44d3a385654d4f19ff40b25959736a656e88
      61/
        28299bd44aa17c44f55d4e66dcd370db16b6d4
      16/
        9d93eea5dacd652e312650e4dcdaf5c93a5cef
        ad67f92060d16cf573c9958762c1b194530d6c
      be/
        a92481f602ce681017db15c0ec163b57789150
        2f6a88600728c950a17b1d4877

      7a/
        8353b04e23e2484a3c221b060b04523cc9fa6e
        55e46531ea83dbce7884e23d87f6be990512cd
      0f/
        66652385056cc4ee701ec63ff23b0b5fb61c5c
        d3065ccafb6fc2e2d3b8a16347d53d2e8b7fdd
      27/
        bc53a753178c5dd1bb4674a95e976ecf1f4558
      c5/
        b3a729bd616c694be876b7523aea448ced683a
      d2/
        40ced3e59868b2f2a1a81278ad29e41b487bcb
        a1613650dae61d80468b5a0b956138b78e346a
  notebooks/
    fv_demo.ipynb
  dataset_files/
    README.md
    extractive/
      color_v_animal_5.json
      adjective_v_verb_5.json
      alphabetically_last_5.json
      choose_middle_of_5.json
      animal_v_object_3.json
      conll2003_organization.json
      conll2003_person.json
      fruit_v_animal_3.json
      alphabetically_first_3.json
      choose_first_of_5.json
      verb_v_adjective_5.json
      concept_v_object_3.json
      squad_val.json
      object_v_concept_5.json
      choose_last_of_5.json
      choose_first_of_3.json
      alphabetically_firs

## Step 1: Read the Plan File

Let's first examine the plan to understand the intended implementation.

In [4]:
# Read the plan file
plan_path = os.path.join(repo_path, "plan.md")
with open(plan_path, 'r') as f:
    plan_content = f.read()
print(plan_content)

# Plan
## Objective
To investigate whether autoregressive transformer language models develop compact vector representations of input-output functions (called function vectors) within their hidden states during in-context learning, and to characterize these representations across diverse tasks and models.

## Hypothesis
1. A small number of attention heads transport a compact representation of the demonstrated task (function vector) that is robust to changes in context and can trigger task execution in zero-shot and natural text settings.
2. Function vectors contain information encoding the output space of the function, but this information alone is not sufficient to reconstruct a working function vector.
3. Function vectors can be composed through vector algebra to create vectors that trigger new complex tasks combining constituent tasks.

## Methodology
1. Apply causal mediation analysis to identify attention heads with highest average indirect effect (AIE) across diverse ICL tasks. 

## Step 2: Read the Documentation File

Now let's examine the documentation (PDF) to find the conclusions made.

In [5]:
# Install PyPDF2 for PDF reading
import subprocess
subprocess.run(['pip', 'install', 'PyPDF2', '-q'])

import PyPDF2

doc_path = os.path.join(repo_path, "documentation.pdf")
with open(doc_path, 'rb') as f:
    reader = PyPDF2.PdfReader(f)
    doc_content = ""
    for page in reader.pages:
        doc_content += page.extract_text() + "\n"
        
print(doc_content)

Published as a conference paper at ICLR 2024
FUNCTION VECTORS IN LARGE LANGUAGE MODELS
Eric Todd∗, Millicent L. Li, Arnab Sen Sharma, Aaron Mueller,
Byron C. Wallace, and David Bau
Khoury College of Computer Sciences, Northeastern University
ABSTRACT
We report the presence of a simple neural mechanism that represents an input-
output function as a vector within autoregressive transformer language models
(LMs). Using causal mediation analysis on a diverse range of in-context-learning
(ICL) tasks, we find that a small number attention heads transport a compact
representation of the demonstrated task, which we call a function vector (FV). FVs
are robust to changes in context, i.e., they trigger execution of the task on inputs
such as zero-shot and natural text settings that do not resemble the ICL contexts
from which they are collected. We test FVs across a range of tasks, models, and
layers and find strong causal effects across settings in middle layers. We investigate
the internal struc

In [6]:
# Let me read the PDF in chunks and extract the key conclusions
doc_path = os.path.join(repo_path, "documentation.pdf")
with open(doc_path, 'rb') as f:
    reader = PyPDF2.PdfReader(f)
    total_pages = len(reader.pages)
    print(f"Total pages: {total_pages}")
    
    # Read first few pages
    print("="*80)
    print("FIRST 5 PAGES:")
    print("="*80)
    for i in range(min(5, total_pages)):
        print(f"\n--- PAGE {i+1} ---")
        print(reader.pages[i].extract_text()[:3000])

Total pages: 52
FIRST 5 PAGES:

--- PAGE 1 ---
Published as a conference paper at ICLR 2024
FUNCTION VECTORS IN LARGE LANGUAGE MODELS
Eric Todd∗, Millicent L. Li, Arnab Sen Sharma, Aaron Mueller,
Byron C. Wallace, and David Bau
Khoury College of Computer Sciences, Northeastern University
ABSTRACT
We report the presence of a simple neural mechanism that represents an input-
output function as a vector within autoregressive transformer language models
(LMs). Using causal mediation analysis on a diverse range of in-context-learning
(ICL) tasks, we find that a small number attention heads transport a compact
representation of the demonstrated task, which we call a function vector (FV). FVs
are robust to changes in context, i.e., they trigger execution of the task on inputs
such as zero-shot and natural text settings that do not resemble the ICL contexts
from which they are collected. We test FVs across a range of tasks, models, and
layers and find strong causal effects across settings in m

Published as a conference paper at ICLR 2024
Function vectors arise naturally when applying causal mediation analysis (Pearl, 2001; Vig et al.,
2020; Meng et al., 2022; 2023; Wang et al., 2022a) to identify the flow of information during ICL.
We describe an activation patching procedure to determine the presence of a handful of attention
heads that mediate many ICL tasks. These heads work together to transport a function vector that
describes the task; the FV can be formed by summing outputs of the causal attention heads.
We test the hypothesis that function vectors are a general mechanism spanning many types of
functions. To quantify the role and efficacy of function vectors, we curate a data set of over 40 diverse
ICL tasks of varying complexity. We calculate FVs for these tasks and investigate impact of FVs in
triggering those functions across a variety of LMs scaling up from 6B to 70B parameters.
We further ask whether FVs are portable: are the effects of an FV limited to contexts 

Published as a conference paper at ICLR 2024
AIE
LayerHead Index(a)
 (b)
<s>
eggs
oeufs
sad
triste
sugar
sucre
good
bon
loan
prêt
read
:Antonym
English-French
Attention Weight
Figure 3: (a) Average indirect effect across all tasks Tfor each attention head in GPT-J, and (b) the
top 10 heads’ weights on individual tokens for one example prompt pt
i. The most strongly implicated
heads appear in middle layers. Attention weights are strongest on the output tokens of each exemplar.
To identify the set of attention heads with the strongest causal effects, we repeat this process for each
attention head aℓjinf, for all layers ℓ, and all head indices j. We gather the attention heads with
highest AIE over all layers as the set A.1
Figure 3a shows the AIE per attention head in GPT-J over many tasks (see Appendix G for larger
models). The 10 attention heads with highest AIE (which make up A) are highlighted in pink (square
outlines) and are clustered primarily in early-middle layers of the network.

In [7]:
# Read the results sections of the documentation - looking for specific numbers
with open(doc_path, 'rb') as f:
    reader = PyPDF2.PdfReader(f)
    
    # Read pages 5-15 for more results
    print("="*80)
    print("PAGES 6-12 (Results sections):")
    print("="*80)
    for i in range(5, min(12, len(reader.pages))):
        print(f"\n--- PAGE {i+1} ---")
        print(reader.pages[i].extract_text()[:4000])

PAGES 6-12 (Results sections):

--- PAGE 6 ---


Published as a conference paper at ICLR 2024
0
5
10
15
20
25
0
0.5
1GPT-JAntonym
0
5
10
15
20
25
Capitalize
0
5
10
15
20
25
Country-Capital
0
5
10
15
20
25
English-French
0
5
10
15
20
25
Present-Past
0
5
10
15
20
25
Singular-Plural
0
8
16
24
32
40
0
0.5
1GPT-NeoX
0
8
16
24
32
40
 0
8
16
24
32
40
 0
8
16
24
32
40
 0
8
16
24
32
40
 0
8
16
24
32
40
0
16
32
48
64
Layer
0
0.5
1Llama 2 (70B)
0
16
32
48
64
Layer
0
16
32
48
64
Layer
0
16
32
48
64
Layer
0
16
32
48
64
Layer
0
16
32
48
64
Layer
Accuracy
Figure 4: Task accuracy across tasks and models, applying FVs in zero-shot settings. We show
accuracies before adding the function vector (dotted lines) and after adding the FV to a specific layer
(solid lines). Adding the FV to early-middle layers pushes models to perform the target task without
any exemplars, as demonstrated by accuracy increases over the zero-shot without FVs.
Table 3: Natural text portability of the Antonym FV . We provide a natural template and substitute in a
query word for 

Published as a conference paper at ICLR 2024
than 100 vocabulary tokens. In other words, knowledge of the top decoded tokens of D(vt)is usually
not enough on its own to construct a working function vector. That suggests that the FV contains
some needed information beyond that expressed by its top decoded tokens.
3.3 V ECTOR ALGEBRA ON FUNCTION VECTORS
Task Expected Output(a)  Input:  "Italy, Russia, China, Japan, France"
vAD(b)vBD
vACvBC*
+
−+First-Copy
Last-CopyFirst-Capital
Last-CapitalItaly
FranceRome
Paris∑FV
vAC
vBCvAD
vBD*
Figure 5: (a) A set of three list-oriented tasks that can be composed to a fourth task using FV vector algebra.
(b) The parallelogram arrangement of the fourth vector v∗
BDwhen it is composed out of the other three FVs.
Although Table 6 suggests that function vectors cannot be understood as simple semantic vector
offsets on word embeddings, we can ask whether function vectors obey semantic vector algebra over
the more abstract space of functional behavior by te

Published as a conference paper at ICLR 2024
Gabriel Ilharco, Marco Tulio Ribeiro, Mitchell Wortsman, Ludwig Schmidt, Hannaneh Hajishirzi,
and Ali Farhadi. Editing models with task arithmetic. In The Eleventh International Conference
on Learning Representations , 2023.
Sarthak Jain and Byron C Wallace. Attention is not explanation. In Proceedings of the 2019
Conference of the North American Chapter of the Association for Computational Linguistics:
Human Language Technologies, Volume 1 (Long and Short Papers) , pp. 3543–3556, 2019.
Goro Kobayashi, Tatsuki Kuribayashi, Sho Yokoi, and Kentaro Inui. Attention is not only a weight:
Analyzing transformers with vector norms. In Proceedings of the 2020 Conference on Empirical
Methods in Natural Language Processing (EMNLP) , pp. 7057–7075, 2020.
Olga Kovaleva, Alexey Romanov, Anna Rogers, and Anna Rumshisky. Revealing the dark secrets
of BERT. In Proceedings of the 2019 Conference on Empirical Methods in Natural Language
Processing and the 9th 

## Step 3: Read the Implementation Notebook

Let's examine the implementation notebook(s) to understand the original results recorded.

In [8]:
# Read the notebook
notebook_path = os.path.join(repo_path, "notebooks", "fv_demo.ipynb")

import json
with open(notebook_path, 'r') as f:
    notebook = json.load(f)
    
# Print notebook structure and cells
print(f"Number of cells: {len(notebook['cells'])}")
print("\n" + "="*80)
print("NOTEBOOK CONTENTS:")
print("="*80)

for i, cell in enumerate(notebook['cells']):
    cell_type = cell['cell_type']
    source = ''.join(cell.get('source', []))
    outputs = cell.get('outputs', [])
    
    print(f"\n--- Cell {i+1} ({cell_type}) ---")
    print(source[:2000] if len(source) > 2000 else source)
    
    if outputs and cell_type == 'code':
        print("\n[OUTPUT:]")
        for output in outputs[:3]:  # Limit outputs shown
            if output.get('output_type') == 'stream':
                text = ''.join(output.get('text', []))[:1000]
                print(text)
            elif output.get('output_type') == 'execute_result':
                data = output.get('data', {})
                if 'text/plain' in data:
                    print(''.join(data['text/plain'])[:1000])

Number of cells: 19

NOTEBOOK CONTENTS:

--- Cell 1 (code) ---
%load_ext autoreload
%autoreload 2

--- Cell 2 (code) ---
import os, re, json
import torch, numpy as np

import sys
sys.path.append('..')
torch.set_grad_enabled(False)

from src.utils.extract_utils import get_mean_head_activations, compute_universal_function_vector
from src.utils.intervention_utils import fv_intervention_natural_text, function_vector_intervention
from src.utils.model_utils import load_gpt_model_and_tokenizer
from src.utils.prompt_utils import load_dataset, word_pairs_to_prompt_data, create_prompt
from src.utils.eval_utils import decode_to_vocab, sentence_eval

--- Cell 3 (markdown) ---
## Load model & tokenizer

--- Cell 4 (code) ---
model_name = 'EleutherAI/gpt-j-6b'
model, tokenizer, model_config = load_gpt_model_and_tokenizer(model_name)
EDIT_LAYER = 9

--- Cell 5 (markdown) ---
## Load dataset and Compute task-conditioned mean activations

--- Cell 6 (code) ---
dataset = load_dataset('antonym', seed=0)


## Step 4: Read the Code Implementation Files

Now let's examine the source code files to understand the implementation details.

In [9]:
# Read all source files
src_path = os.path.join(repo_path, "src")

# List all Python files
python_files = []
for root, dirs, files in os.walk(src_path):
    for f in files:
        if f.endswith('.py') and not f.startswith('__'):
            python_files.append(os.path.join(root, f))

print(f"Found {len(python_files)} Python files:")
for f in python_files:
    print(f"  - {f}")

Found 14 Python files:
  - /net/scratch2/smallyan/function_vectors_eval/src/portability_eval.py
  - /net/scratch2/smallyan/function_vectors_eval/src/test_numheads.py
  - /net/scratch2/smallyan/function_vectors_eval/src/compute_indirect_effect.py
  - /net/scratch2/smallyan/function_vectors_eval/src/vocab_reconstruction.py
  - /net/scratch2/smallyan/function_vectors_eval/src/compute_avg_hidden_state.py
  - /net/scratch2/smallyan/function_vectors_eval/src/natural_text_eval.py
  - /net/scratch2/smallyan/function_vectors_eval/src/evaluate_function_vector.py
  - /net/scratch2/smallyan/function_vectors_eval/src/compute_average_activations.py
  - /net/scratch2/smallyan/function_vectors_eval/src/utils/eval_utils.py
  - /net/scratch2/smallyan/function_vectors_eval/src/utils/prompt_utils.py
  - /net/scratch2/smallyan/function_vectors_eval/src/utils/intervention_utils.py
  - /net/scratch2/smallyan/function_vectors_eval/src/utils/extract_utils.py
  - /net/scratch2/smallyan/function_vectors_eval/src

In [10]:
# Read key implementation files to understand the implementation
# Start with evaluate_function_vector.py

evaluate_fv_path = os.path.join(repo_path, "src", "evaluate_function_vector.py")
with open(evaluate_fv_path, 'r') as f:
    evaluate_fv_content = f.read()
print("evaluate_function_vector.py:")
print("="*80)
print(evaluate_fv_content[:5000])

evaluate_function_vector.py:
import os, json
import torch, numpy as np
import argparse

# Include prompt creation helper functions
from utils.prompt_utils import *
from utils.intervention_utils import *
from utils.model_utils import *
from utils.eval_utils import *
from utils.extract_utils import *
from compute_indirect_effect import compute_indirect_effect

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser()

    parser.add_argument('--dataset_name', help='Name of the dataset to be loaded', type=str, required=True)
    parser.add_argument('--n_top_heads', help='Number of attenion head outputs used to compute function vector', required=False, type=int, default=10)
    parser.add_argument('--edit_layer', help='Layer for intervention. If -1, sweep over all layers', type=int, required=False, default=-1) # 
    parser.add_argument('--model_name', help='Name of model to be loaded', type=str, required=False, default='EleutherAI/gpt-j-6b')
    parser.add_argument('--root_da

In [11]:
# Read the rest of evaluate_function_vector.py
print(evaluate_fv_content[5000:10000])

ta_dir, test_size=test_split, seed=seed)

    if not os.path.exists(save_path_root):
        os.makedirs(save_path_root)

    print(f"Filtering Dataset via {n_shots}-shot Eval")
    # 1. Compute Model 10-shot Baseline & 2. Filter test set to cases where model gets it correct

    fs_results_file_name = f'{save_path_root}/fs_results_layer_sweep.json'
    print(fs_results_file_name)
    if os.path.exists(fs_results_file_name):
        with open(fs_results_file_name, 'r') as indata:
            fs_results = json.load(indata)
        key = 'score' if generate_str else 'clean_rank_list'
        target_val = 1 if generate_str else 0
        filter_set = np.where(np.array(fs_results[key]) == target_val)[0]
        filter_set_validation = None
    elif generate_str:
        set_seed(seed+42)
        fs_results_validation = n_shot_eval_no_intervention(dataset=dataset, n_shots=n_shots, model=model, model_config=model_config, tokenizer=tokenizer, compute_ppl=False,
                               

In [12]:
# Read the rest of evaluate_function_vector.py
print(evaluate_fv_content[10000:])

 Eval with edit_layer={eval_edit_layer}")
        set_seed(seed)
        if generate_str:
            pred_filepath = f"{save_path_root}/preds/{model_config['name_or_path'].replace('/', '_')}_ZS_intervention_layer{eval_edit_layer}.txt"
            zs_results = n_shot_eval(dataset=dataset, fv_vector=fv, edit_layer=eval_edit_layer, n_shots=0,
                                     model=model, model_config=model_config, tokenizer=tokenizer, filter_set=filter_set,
                                     generate_str=generate_str, metric=metric, pred_filepath=pred_filepath, prefixes=prefixes, separators=separators)
        else:
            zs_results = n_shot_eval(dataset=dataset, fv_vector=fv, edit_layer=eval_edit_layer, n_shots=0,
                                    model=model, model_config=model_config, tokenizer=tokenizer, filter_set=filter_set, prefixes=prefixes, separators=separators)
        zs_results_file_suffix = f'_editlayer_{eval_edit_layer}.json'   


        print(f"Running {n_s

In [13]:
# Read key utility files
# compute_indirect_effect.py
indirect_effect_path = os.path.join(repo_path, "src", "compute_indirect_effect.py")
with open(indirect_effect_path, 'r') as f:
    ie_content = f.read()
print("compute_indirect_effect.py:")
print("="*80)
print(ie_content)

compute_indirect_effect.py:
import os, re, json
from tqdm import tqdm
import torch, numpy as np
import argparse
from baukit import TraceDict

# Include prompt creation helper functions
from utils.prompt_utils import *
from utils.intervention_utils import *
from utils.model_utils import *
from utils.extract_utils import *


def activation_replacement_per_class_intervention(prompt_data, avg_activations, dummy_labels, model, model_config, tokenizer, last_token_only=True):
    """
    Experiment to determine top intervention locations through avg activation replacement. 
    Performs a systematic sweep over attention heads (layer, head) to track their causal influence on probs of key tokens.

    Parameters: 
    prompt_data: dict containing ICL prompt examples, and template information
    avg_activations: avg activation of each attention head in the model taken across n_trials ICL prompts
    dummy_labels: labels and indices for a baseline prompt with the same number of example pairs
   

In [14]:
# Read portability_eval.py and natural_text_eval.py
portability_path = os.path.join(repo_path, "src", "portability_eval.py")
natural_text_path = os.path.join(repo_path, "src", "natural_text_eval.py")

with open(portability_path, 'r') as f:
    portability_content = f.read()
    
with open(natural_text_path, 'r') as f:
    natural_text_content = f.read()
    
print("portability_eval.py:")
print("="*80)
print(portability_content[:3000])
print("\n\nnatural_text_eval.py:")
print("="*80)
print(natural_text_content[:3000])

portability_eval.py:
import os, json
import torch, numpy as np
import argparse

# Include prompt creation helper functions
from utils.prompt_utils import *
from utils.intervention_utils import *
from utils.model_utils import *
from utils.eval_utils import *
from utils.extract_utils import *


if __name__ == "__main__":
    
    parser = argparse.ArgumentParser()

    parser.add_argument('--dataset_name', help='Name of the dataset to be loaded', type=str, required=True)
    parser.add_argument('--n_eval_templates', help='Number of templates to evaluate with', required=True, type=int, default=15)
    parser.add_argument('--edit_layer', help='Layer for intervention. If -1, sweep over all layers', type=int, required=False, default=9) # 

    parser.add_argument('--n_top_heads', help='Number of attenion head outputs used to compute function vector', required=False, type=int, default=10)
    parser.add_argument('--model_name', help='Name of model to be loaded', type=str, required=False, defa

In [15]:
# Read vocab_reconstruction.py for decoded vocabulary analysis
vocab_reconstruction_path = os.path.join(repo_path, "src", "vocab_reconstruction.py")
with open(vocab_reconstruction_path, 'r') as f:
    vocab_reconstruction_content = f.read()
    
print("vocab_reconstruction.py:")
print("="*80)
print(vocab_reconstruction_content)

vocab_reconstruction.py:
import os
import torch, numpy as np
import argparse

# Include prompt creation helper functions
from utils.prompt_utils import load_dataset
from utils.extract_utils import get_mean_head_activations, compute_universal_function_vector
from utils.eval_utils import n_shot_eval_no_intervention, n_shot_eval
from utils.model_utils import load_gpt_model_and_tokenizer, set_seed

def optim_loop(v_n, target, decoder, loss_fn, optimizer, n_steps:int=1000, verbose:bool=False, restrict_vocab:int=50400):
    if target.shape[-1] != restrict_vocab:
        inds = torch.topk(target, restrict_vocab).indices[0]
        Z = torch.zeros(target.size()).cuda()
        Z[:,inds] = target[:,inds]
    else:
        Z = target
            
    for i in range(n_steps):
        loss = loss_fn(decoder(v_n),Z)
        loss.backward()
        if verbose:
            print(f"Loss:{loss.item()}, iter:{i}")
        optimizer.step()
        optimizer.zero_grad()
    return v_n

def vocab_reconstru

In [16]:
# Read the Code Walkthrough file for more details about the implementation
walkthrough_path = os.path.join(repo_path, "CodeWalkthrough.md")
with open(walkthrough_path, 'r') as f:
    walkthrough_content = f.read()
    
print("CodeWalkthrough.md:")
print("="*80)
print(walkthrough_content)

CodeWalkthrough.md:
# Function Vectors in Large Language Models
### [Project Website](https://functions.baulab.info) | [Arxiv Preprint](https://arxiv.org/abs/2310.15213) | [OpenReview](https://openreview.net/forum?id=AwyxtyMwaG)

This repository contains data and code for the paper: [Function Vectors in Large Language Models](https://arxiv.org/pdf/2310.15213).

<p align="left">
<img src="https://functions.baulab.info/images/Paper/fv-demonstrations.png" style="width:100%;"/>
</p> 

## Setup

We recommend using conda as a package manager. 
The environment used for this project can be found in the `fv_environment.yml` file.
To install, you can run: 
```
conda env create -f fv_environment.yml
conda activate fv
```

## Demo Notebook
Checkout `notebooks/fv_demo.ipynb` for a jupyter notebook with a demo of how to create a function vector and use it in different contexts.

## Data
The datasets used in our project can be found in the `dataset_files` folder.

## Code
Our main evaluation scripts 

## Step 5: Analysis and Comparison

Now let's analyze the plan vs implementation and documentation vs results for the consistency checks.

In [17]:
# Let's now systematically check the plan vs implementation
# Extract all methodology and experiment steps from the plan

plan_steps = """
PLAN METHODOLOGY:
1. Apply causal mediation analysis to identify attention heads with highest average indirect effect (AIE) across diverse ICL tasks. 
   Extract function vectors by summing task-conditioned mean outputs of top causal attention heads.
2. Test function vectors across models (GPT-J 6B to Llama 2 70B) and over 40 diverse ICL tasks by adding FVs to hidden states 
   at different layers and measuring task performance in shuffled-label, zero-shot, and natural text contexts.
3. Analyze FV internal structure by decoding vectors to vocabulary space and testing whether reconstructed vectors matching 
   decoded distributions can recover FV performance.
4. Test vector algebra composition by constructing decomposable tasks and measuring whether algebraic sums of FVs can execute combined tasks.

PLAN EXPERIMENTS:
1. Portability of function vectors across contexts - Shuffled-label ICL, zero-shot, different ICL templates, natural text
2. Decoded vocabulary analysis - Reconstruct FV from vocabulary tokens
3. Vector algebra composition - Combine FVs algebraically
4. Causal mediation analysis across models - AIE per attention head across models
5. Performance across diverse tasks and models - 34+ additional tasks
6. Natural text portability evaluation - Different natural language prompt templates
"""

print(plan_steps)


PLAN METHODOLOGY:
1. Apply causal mediation analysis to identify attention heads with highest average indirect effect (AIE) across diverse ICL tasks. 
   Extract function vectors by summing task-conditioned mean outputs of top causal attention heads.
2. Test function vectors across models (GPT-J 6B to Llama 2 70B) and over 40 diverse ICL tasks by adding FVs to hidden states 
   at different layers and measuring task performance in shuffled-label, zero-shot, and natural text contexts.
3. Analyze FV internal structure by decoding vectors to vocabulary space and testing whether reconstructed vectors matching 
   decoded distributions can recover FV performance.
4. Test vector algebra composition by constructing decomposable tasks and measuring whether algebraic sums of FVs can execute combined tasks.

PLAN EXPERIMENTS:
1. Portability of function vectors across contexts - Shuffled-label ICL, zero-shot, different ICL templates, natural text
2. Decoded vocabulary analysis - Reconstruct FV f

In [18]:
# Now let's check which implementation files correspond to which plan steps

implementation_mapping = """
IMPLEMENTATION MAPPING:

PLAN STEP 1: Causal Mediation Analysis to identify AIE & Extract Function Vectors
- Implemented in: compute_indirect_effect.py (compute_indirect_effect, activation_replacement_per_class_intervention)
- Implemented in: src/utils/extract_utils.py (get_mean_head_activations, compute_universal_function_vector, compute_function_vector)
✓ FOUND

PLAN STEP 2: Test FVs across models & tasks (shuffled-label, zero-shot, natural text)
- Implemented in: evaluate_function_vector.py (n_shot_eval with shuffle_labels, zero-shot eval with n_shots=0)
- Implemented in: src/utils/eval_utils.py (n_shot_eval, n_shot_eval_no_intervention)
- Implemented in: natural_text_eval.py (natural_text_eval function)
✓ FOUND

PLAN STEP 3: Decoded vocabulary analysis
- Implemented in: vocab_reconstruction.py (optim_loop, vocab_reconstruction functions)
✓ FOUND

PLAN STEP 4: Vector algebra composition
- NOT directly found in implementation files - mentioned in documentation but no explicit implementation script
? NOT FOUND (need to verify)

PLAN EXPERIMENTS:
1. Portability across contexts - portability_eval.py ✓
2. Decoded vocabulary analysis - vocab_reconstruction.py ✓
3. Vector algebra composition - NOT FOUND ?
4. Causal mediation across models - compute_indirect_effect.py (supports different models via command line args) ✓
5. Performance across diverse tasks - evaluate_function_vector.py with dataset_files/ ✓
6. Natural text portability - natural_text_eval.py ✓
"""

print(implementation_mapping)


IMPLEMENTATION MAPPING:

PLAN STEP 1: Causal Mediation Analysis to identify AIE & Extract Function Vectors
- Implemented in: compute_indirect_effect.py (compute_indirect_effect, activation_replacement_per_class_intervention)
- Implemented in: src/utils/extract_utils.py (get_mean_head_activations, compute_universal_function_vector, compute_function_vector)
✓ FOUND

PLAN STEP 2: Test FVs across models & tasks (shuffled-label, zero-shot, natural text)
- Implemented in: evaluate_function_vector.py (n_shot_eval with shuffle_labels, zero-shot eval with n_shots=0)
- Implemented in: src/utils/eval_utils.py (n_shot_eval, n_shot_eval_no_intervention)
- Implemented in: natural_text_eval.py (natural_text_eval function)
✓ FOUND

PLAN STEP 3: Decoded vocabulary analysis
- Implemented in: vocab_reconstruction.py (optim_loop, vocab_reconstruction functions)
✓ FOUND

PLAN STEP 4: Vector algebra composition
- NOT directly found in implementation files - mentioned in documentation but no explicit implem

In [19]:
# Let's search for vector algebra / composition implementation
# Search in extract_utils.py and intervention_utils.py

extract_utils_path = os.path.join(repo_path, "src", "utils", "extract_utils.py")
intervention_utils_path = os.path.join(repo_path, "src", "utils", "intervention_utils.py")

with open(extract_utils_path, 'r') as f:
    extract_utils_content = f.read()

with open(intervention_utils_path, 'r') as f:
    intervention_utils_content = f.read()

print("Searching for vector algebra/composition in extract_utils.py:")
print("="*80)
if 'compos' in extract_utils_content.lower() or 'algebra' in extract_utils_content.lower():
    print("Found composition/algebra related code")
else:
    print("No composition/algebra related code found")

print("\nSearching in intervention_utils.py:")
if 'compos' in intervention_utils_content.lower() or 'algebra' in intervention_utils_content.lower():
    print("Found composition/algebra related code")
else:
    print("No composition/algebra related code found")

# Search all files for vector composition
print("\n\nSearching all Python files for vector composition/algebra:")
for f in python_files:
    with open(f, 'r') as file:
        content = file.read().lower()
        if 'compos' in content or 'algebra' in content or 'v_bd' in content or 'vbd' in content:
            print(f"Found in: {f}")

Searching for vector algebra/composition in extract_utils.py:
No composition/algebra related code found

Searching in intervention_utils.py:
No composition/algebra related code found


Searching all Python files for vector composition/algebra:


In [20]:
# The vector algebra composition experiment is described in the plan but not found in the implementation
# Let's verify what functionality exists to do the composition

# According to the documentation, vector algebra composition involves:
# v*_BD = vAD + vBC - vAC
# This is a simple vector addition/subtraction that could be done outside the provided scripts

# Let's check if the demo notebook has any composition example
print("Checking if notebook has any composition examples:")
print("="*80)
for i, cell in enumerate(notebook['cells']):
    source = ''.join(cell.get('source', []))
    if 'compos' in source.lower() or 'algebra' in source.lower() or 'vbd' in source.lower() or 'v_bd' in source.lower():
        print(f"Cell {i+1}: Found composition related code")
        print(source[:500])
        
print("\nNo explicit composition implementation found in the demo notebook.")

Checking if notebook has any composition examples:

No explicit composition implementation found in the demo notebook.


In [21]:
# Now let's extract key numerical results from the documentation and verify they match
# Key results from documentation (Table 2):

documentation_results = """
KEY RESULTS FROM DOCUMENTATION:

Table 2 - Average accuracy across 6 tasks (macro-averaged across random seeds):
=========================================================================
                                    Shuffled-Label    Zero-Shot
GPT-J (baseline)                    39.1±1.2%         5.5±0.8%
GPT-J + layer avg (Section 2.1)     79.5±3.1%         9.5±1.8%
GPT-J + FV                          90.8±0.9%         57.5±1.7%

GPT-NeoX (baseline)                 32.5±1.3%         6.7±0.1%
GPT-NeoX + FV                       90.7±0.6%         57.1±1.5%

Llama 2 (70B) (baseline)            52.3±2.2%         8.2±0.7%
Llama 2 (70B) + FV                  96.5±0.5%         83.8±0.7%

GPT-J + FV (34 additional tasks)    80.4±0.6%         46.1±3.7%
Llama 2 (70B) + FV (34 add tasks)   93.0±0.5%         74.2±3.1%

Table 3 - Natural text portability of the Antonym FV:
=========================================================================
Prompt                                          GPT-J      +Antonym FV
"The word 'x' means"                            1.5±1.1%   55.2±3.8%
"When I think of the word 'x'..."               0.3±0.2%   67.7±3.0%
"When I think of x, I usually"                  0.0±0.0%   61.1±2.4%
"While reading a book..."                       2.7±1.9%   46.0±4.6%
"The word x can be understood as..."            2.4±1.7%   52.7±11.0%

Table 6 - Vocabulary reconstruction results (Zero-shot accuracy):
=========================================================================
Task             v_t       ˆv_t100   KL100      ˆv_tall    KLall
Antonym          48.2±2.0% 4.8±2.0%  0.0033    39.6±2.6%  0.0137
Capitalize       70.5±2.4% 5.7±2.2%  0.0001    51.5±11.6% 0.0053
Country-Capital  83.2±2.7% 58.1±18.5% 0.0002   29.0±15.1% 0.0019
English-French   44.7±1.2% 4.8±1.7%  0.0       42.0±5.6%  0.0056
Present-Past     19.7±5.9% 4.4±1.4%  0.0052    6.8±2.6%   0.0139
Singular-Plural  47.0±3.4% 23.3±6.1% 0.0       27.4±4.7%  0.0145

Table 7 - Vector algebra composition (List-oriented tasks):
=========================================================================
Task                       ICL(ten-shot)  vBD(FV)     v*BD(sum)
Last-Antonym               0.25±0.02      0.02±0.01   0.07±0.02
Last-Capitalize            0.91±0.02      0.64±0.03   0.76±0.04
Last-Country-Capital       0.32±0.02      0.15±0.03   0.60±0.02
Last-English-French        0.45±0.04      0.16±0.02   0.06±0.02
Last-Present-Past          0.89±0.02      0.18±0.02   0.29±0.03
Last-Singular-Plural       0.90±0.01      0.28±0.01   0.29±0.02
Last-Capitalize-First-Ltr  0.75±0.01      0.76±0.02   0.95±0.00
Last-Product-Company       0.35±0.03      0.30±0.02   0.41±0.03
"""

print(documentation_results)


KEY RESULTS FROM DOCUMENTATION:

Table 2 - Average accuracy across 6 tasks (macro-averaged across random seeds):
                                    Shuffled-Label    Zero-Shot
GPT-J (baseline)                    39.1±1.2%         5.5±0.8%
GPT-J + layer avg (Section 2.1)     79.5±3.1%         9.5±1.8%
GPT-J + FV                          90.8±0.9%         57.5±1.7%

GPT-NeoX (baseline)                 32.5±1.3%         6.7±0.1%
GPT-NeoX + FV                       90.7±0.6%         57.1±1.5%

Llama 2 (70B) (baseline)            52.3±2.2%         8.2±0.7%
Llama 2 (70B) + FV                  96.5±0.5%         83.8±0.7%

GPT-J + FV (34 additional tasks)    80.4±0.6%         46.1±3.7%
Llama 2 (70B) + FV (34 add tasks)   93.0±0.5%         74.2±3.1%

Table 3 - Natural text portability of the Antonym FV:
Prompt                                          GPT-J      +Antonym FV
"The word 'x' means"                            1.5±1.1%   55.2±3.8%
"When I think of the word 'x'..."               0.3±

In [22]:
# Now let's compare these with the Plan's stated results
plan_results = """
PLAN'S STATED RESULTS (for comparison):

Portability of function vectors across contexts:
- Shuffled-label: GPT-J+FV achieves 90.8% vs 39.1% baseline ✓ MATCHES DOC
- Zero-shot: GPT-J+FV achieves 57.5% vs 5.5% baseline ✓ MATCHES DOC
- FVs work best at layer L/3 (approx.) ✓ MATCHES DOC (evaluated at layers 9, 15, 26 for GPT-J, GPT-NeoX, Llama)
- FVs robust across 20 different templates ✓ MATCHES DOC (76.2% shuffled, 40.0% zero-shot avg mentioned)

Decoded vocabulary analysis:
- Reconstructed vectors matching top 100 tokens achieve lower performance than original FVs
- Country-Capital example: 58.1% (ˆv100) vs 83.2% (vt) ✓ MATCHES DOC Table 6
- Even matching all tokens underperforms - indicating FVs carry information beyond output vocabulary ✓ MATCHES DOC

Vector algebra composition:
- Last-Country-Capital: composed v*BD=0.60 vs ICL=0.32 ✓ MATCHES DOC Table 7
- Last-Capitalize-First-Letter: v*BD=0.95 vs ICL=0.75 ✓ MATCHES DOC Table 7
- Last-Antonym: v*BD=0.07 vs ICL=0.25 (fails) ✓ MATCHES DOC Table 7

Causal mediation analysis:
- Top 10-100 attention heads cluster in middle layers ✓ MATCHES DOC
- Maximum AIE decreases with model size (~0.053 GPT-J to ~0.037 Llama 70B) ✓ STATED in plan, matches appendix

Natural text portability:
- Antonym FV achieves 55-68% vs 0-3% baseline ✓ MATCHES DOC Table 3
- Country-Capital FV achieves 57-72% vs 4-23% baseline (stated in plan, supported by doc)
"""

print(plan_results)


PLAN'S STATED RESULTS (for comparison):

Portability of function vectors across contexts:
- Shuffled-label: GPT-J+FV achieves 90.8% vs 39.1% baseline ✓ MATCHES DOC
- Zero-shot: GPT-J+FV achieves 57.5% vs 5.5% baseline ✓ MATCHES DOC
- FVs work best at layer L/3 (approx.) ✓ MATCHES DOC (evaluated at layers 9, 15, 26 for GPT-J, GPT-NeoX, Llama)
- FVs robust across 20 different templates ✓ MATCHES DOC (76.2% shuffled, 40.0% zero-shot avg mentioned)

Decoded vocabulary analysis:
- Reconstructed vectors matching top 100 tokens achieve lower performance than original FVs
- Country-Capital example: 58.1% (ˆv100) vs 83.2% (vt) ✓ MATCHES DOC Table 6
- Even matching all tokens underperforms - indicating FVs carry information beyond output vocabulary ✓ MATCHES DOC

Vector algebra composition:
- Last-Country-Capital: composed v*BD=0.60 vs ICL=0.32 ✓ MATCHES DOC Table 7
- Last-Capitalize-First-Letter: v*BD=0.95 vs ICL=0.75 ✓ MATCHES DOC Table 7
- Last-Antonym: v*BD=0.07 vs ICL=0.25 (fails) ✓ MATCHE

In [23]:
# CS1: Verify conclusions against original results
# The documentation comes from a published ICLR 2024 paper - all results are internally consistent

cs1_analysis = """
CS1 ANALYSIS: CONCLUSION VS ORIGINAL RESULTS
=============================================

The documentation is a published paper (ICLR 2024). The conclusions stated match the results 
presented in the tables:

1. Main claim: FVs enable task performance in shuffled-label and zero-shot settings
   - Table 2 shows GPT-J+FV: 90.8% shuffled, 57.5% zero-shot vs baseline 39.1%, 5.5%
   - Results and conclusions MATCH ✓

2. Portability claim: FVs work across different templates and natural text
   - Table 3 shows Antonym FV: 55-68% vs 0-3% baseline
   - Results and conclusions MATCH ✓

3. Vocabulary reconstruction claim: Top tokens not sufficient to reconstruct FV
   - Table 6 shows ˆv100 underperforms vt (e.g., 58.1% vs 83.2% for Country-Capital)
   - Results and conclusions MATCH ✓

4. Vector algebra claim: Some FVs can be composed, others cannot
   - Table 7 shows Last-Country-Capital v*BD=0.60 outperforms ICL=0.32
   - Table 7 shows Last-Antonym v*BD=0.07 underperforms ICL=0.25
   - Results and conclusions MATCH ✓

5. Layer analysis claim: FVs work best at early-middle layers (L/3)
   - Figure 4 shows accuracy peaks at layer 9 for GPT-J (28 layers), 15 for GPT-NeoX
   - Results and conclusions MATCH ✓

VERDICT: All evaluable conclusions in the documentation match the recorded results.
CS1: PASS
"""

print(cs1_analysis)


CS1 ANALYSIS: CONCLUSION VS ORIGINAL RESULTS

The documentation is a published paper (ICLR 2024). The conclusions stated match the results 
presented in the tables:

1. Main claim: FVs enable task performance in shuffled-label and zero-shot settings
   - Table 2 shows GPT-J+FV: 90.8% shuffled, 57.5% zero-shot vs baseline 39.1%, 5.5%
   - Results and conclusions MATCH ✓

2. Portability claim: FVs work across different templates and natural text
   - Table 3 shows Antonym FV: 55-68% vs 0-3% baseline
   - Results and conclusions MATCH ✓

3. Vocabulary reconstruction claim: Top tokens not sufficient to reconstruct FV
   - Table 6 shows ˆv100 underperforms vt (e.g., 58.1% vs 83.2% for Country-Capital)
   - Results and conclusions MATCH ✓

4. Vector algebra claim: Some FVs can be composed, others cannot
   - Table 7 shows Last-Country-Capital v*BD=0.60 outperforms ICL=0.32
   - Table 7 shows Last-Antonym v*BD=0.07 underperforms ICL=0.25
   - Results and conclusions MATCH ✓

5. Layer analysi

In [24]:
# CS2: Verify plan steps against implementation
cs2_analysis = """
CS2 ANALYSIS: PLAN VS IMPLEMENTATION
=====================================

PLAN METHODOLOGY STEPS:
-----------------------

Step 1: Apply causal mediation analysis to identify attention heads with highest AIE
        Extract function vectors by summing task-conditioned mean outputs of top causal attention heads.
        
IMPLEMENTATION STATUS: ✓ FOUND
- compute_indirect_effect.py: implements activation_replacement_per_class_intervention() and compute_indirect_effect()
- src/utils/extract_utils.py: implements get_mean_head_activations(), compute_function_vector(), compute_universal_function_vector()
- The FV is computed as sum of top-k attention head outputs: vt = sum(mean_activations[top_heads])

Step 2: Test function vectors across models and 40+ tasks in shuffled-label, zero-shot, natural text contexts
        
IMPLEMENTATION STATUS: ✓ FOUND
- evaluate_function_vector.py: implements n_shot_eval() with shuffle_labels flag, zero-shot (n_shots=0)
- natural_text_eval.py: implements natural_text_eval() for natural text contexts
- portability_eval.py: implements evaluation across different ICL templates
- dataset_files/: contains 40+ task datasets (abstractive/, extractive/)
- Model support via command line --model_name argument

Step 3: Analyze FV internal structure by decoding to vocabulary space and testing reconstruction
        
IMPLEMENTATION STATUS: ✓ FOUND
- vocab_reconstruction.py: implements optim_loop() and vocab_reconstruction() 
- Reconstructs vectors by optimizing to match decoded distribution with restrict_vocab_list=[100, 50400]

Step 4: Test vector algebra composition
        
IMPLEMENTATION STATUS: ✗ NOT FOUND
- No explicit script for vector algebra composition experiments
- The computation v*BD = vAD + vBC - vAC is simple vector arithmetic but no script to systematically run this experiment
- Missing: Script to extract FVs for First-Copy, Last-Copy, First-Capital tasks and compute composed vectors
- Missing: Evaluation script for composed vectors on list-oriented tasks

PLAN EXPERIMENTS:
-----------------
1. Portability across contexts          ✓ FOUND (portability_eval.py)
2. Decoded vocabulary analysis          ✓ FOUND (vocab_reconstruction.py)
3. Vector algebra composition           ✗ NOT FOUND
4. Causal mediation across models       ✓ FOUND (compute_indirect_effect.py with --model_name)
5. Performance across 34+ tasks         ✓ FOUND (evaluate_function_vector.py, dataset_files/)
6. Natural text portability             ✓ FOUND (natural_text_eval.py)

VERDICT: One plan step (vector algebra composition - Step 4 / Experiment 3) is missing from implementation.
CS2: FAIL - Vector algebra composition experiment not implemented
"""

print(cs2_analysis)


CS2 ANALYSIS: PLAN VS IMPLEMENTATION

PLAN METHODOLOGY STEPS:
-----------------------

Step 1: Apply causal mediation analysis to identify attention heads with highest AIE
        Extract function vectors by summing task-conditioned mean outputs of top causal attention heads.
        
IMPLEMENTATION STATUS: ✓ FOUND
- compute_indirect_effect.py: implements activation_replacement_per_class_intervention() and compute_indirect_effect()
- src/utils/extract_utils.py: implements get_mean_head_activations(), compute_function_vector(), compute_universal_function_vector()
- The FV is computed as sum of top-k attention head outputs: vt = sum(mean_activations[top_heads])

Step 2: Test function vectors across models and 40+ tasks in shuffled-label, zero-shot, natural text contexts
        
IMPLEMENTATION STATUS: ✓ FOUND
- evaluate_function_vector.py: implements n_shot_eval() with shuffle_labels flag, zero-shot (n_shots=0)
- natural_text_eval.py: implements natural_text_eval() for natural text cont

## Summary of Consistency Evaluation

### CS1: Conclusions vs Original Results - **PASS**
All evaluable conclusions in the documentation match the recorded results.

### CS2: Implementation Follows the Plan - **FAIL**
One plan step (vector algebra composition) is missing from the implementation.

In [25]:
# Create evaluation directory and output files
eval_dir = os.path.join(repo_path, "evaluation")
os.makedirs(eval_dir, exist_ok=True)
print(f"Created evaluation directory: {eval_dir}")

Created evaluation directory: /net/scratch2/smallyan/function_vectors_eval/evaluation


In [26]:
# Create the consistency_evaluation.json file
import json

consistency_evaluation = {
    "Checklist": {
        "CS1_Results_vs_Conclusion": "PASS",
        "CS2_Plan_vs_Implementation": "FAIL"
    },
    "Rationale": {
        "CS1_Results_vs_Conclusion": "All evaluable conclusions in the documentation match the results recorded in the paper. The main claims about FV performance (90.8% shuffled-label, 57.5% zero-shot for GPT-J), natural text portability (55-68% for Antonym), vocabulary reconstruction (58.1% vs 83.2% for Country-Capital), and vector algebra composition results (Last-Country-Capital v*BD=0.60 vs ICL=0.32) all match between conclusions and tabulated results.",
        "CS2_Plan_vs_Implementation": "The plan specifies 4 methodology steps and 6 experiments. Step 4 (Test vector algebra composition) is missing from the implementation. While the plan describes experiments combining FVs algebraically (v*BD = vAD + vBC - vAC) to create composed vectors for list-oriented tasks, no implementation script exists to perform this experiment. The other 5 experiments (portability, vocabulary reconstruction, causal mediation, diverse tasks, natural text) are all implemented in the codebase."
    }
}

json_path = os.path.join(eval_dir, "consistency_evaluation.json")
with open(json_path, 'w') as f:
    json.dump(consistency_evaluation, f, indent=4)

print(f"Created: {json_path}")
print("\nContents:")
print(json.dumps(consistency_evaluation, indent=4))

Created: /net/scratch2/smallyan/function_vectors_eval/evaluation/consistency_evaluation.json

Contents:
{
    "Checklist": {
        "CS1_Results_vs_Conclusion": "PASS",
        "CS2_Plan_vs_Implementation": "FAIL"
    },
    "Rationale": {
        "CS1_Results_vs_Conclusion": "All evaluable conclusions in the documentation match the results recorded in the paper. The main claims about FV performance (90.8% shuffled-label, 57.5% zero-shot for GPT-J), natural text portability (55-68% for Antonym), vocabulary reconstruction (58.1% vs 83.2% for Country-Capital), and vector algebra composition results (Last-Country-Capital v*BD=0.60 vs ICL=0.32) all match between conclusions and tabulated results.",
        "CS2_Plan_vs_Implementation": "The plan specifies 4 methodology steps and 6 experiments. Step 4 (Test vector algebra composition) is missing from the implementation. While the plan describes experiments combining FVs algebraically (v*BD = vAD + vBC - vAC) to create composed vectors for 

In [27]:
# Now create the self_matching.ipynb notebook
# First, let's construct the notebook content

notebook_content = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Self-Matching Consistency Evaluation\n",
                "\n",
                "This notebook documents the consistency evaluation between:\n",
                "1. **CS1**: Documentation conclusions vs original recorded results\n",
                "2. **CS2**: Plan steps vs implementation\n",
                "\n",
                "Repository: `/net/scratch2/smallyan/function_vectors_eval`"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## CS1: Conclusions vs Original Results\n",
                "\n",
                "### Evaluation Criteria\n",
                "**PASS** — All evaluable conclusions in the documentation match the results originally recorded.\n",
                "**FAIL** — At least one evaluable conclusion contradicts the originally recorded results."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Key Claims and Verification\n",
                "\n",
                "| Claim | Documentation Value | Result in Tables | Status |\n",
                "|-------|---------------------|------------------|--------|\n",
                "| GPT-J+FV shuffled-label accuracy | 90.8±0.9% | Table 2: 90.8±0.9% | ✓ MATCH |\n",
                "| GPT-J+FV zero-shot accuracy | 57.5±1.7% | Table 2: 57.5±1.7% | ✓ MATCH |\n",
                "| GPT-J baseline shuffled-label | 39.1±1.2% | Table 2: 39.1±1.2% | ✓ MATCH |\n",
                "| Antonym FV natural text (\"The word x means\") | 55.2±3.8% | Table 3: 55.2±3.8% | ✓ MATCH |\n",
                "| Country-Capital v_t accuracy | 83.2±2.7% | Table 6: 83.2±2.7% | ✓ MATCH |\n",
                "| Country-Capital ˆv_t100 accuracy | 58.1±18.5% | Table 6: 58.1±18.5% | ✓ MATCH |\n",
                "| Last-Country-Capital ICL accuracy | 0.32±0.02 | Table 7: 0.32±0.02 | ✓ MATCH |\n",
                "| Last-Country-Capital v*BD accuracy | 0.60±0.02 | Table 7: 0.60±0.02 | ✓ MATCH |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### CS1 Verdict: **PASS**\n",
                "\n",
                "All evaluable conclusions in the documentation match the results originally recorded in the tables. The paper is internally consistent."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## CS2: Implementation Follows the Plan\n",
                "\n",
                "### Evaluation Criteria\n",
                "**PASS** — A Plan file exists and all plan steps appear in the implementation.\n",
                "**FAIL** — A Plan file exists and at least one plan step is missing in the implementation."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Plan Methodology Steps\n",
                "\n",
                "| Step | Description | Implementation File | Status |\n",
                "|------|-------------|---------------------|--------|\n",
                "| 1 | Causal mediation analysis to identify AIE, extract FVs | `compute_indirect_effect.py`, `extract_utils.py` | ✓ FOUND |\n",
                "| 2 | Test FVs across models & tasks (shuffled, zero-shot, natural text) | `evaluate_function_vector.py`, `natural_text_eval.py`, `portability_eval.py` | ✓ FOUND |\n",
                "| 3 | Decode FVs to vocabulary space, test reconstruction | `vocab_reconstruction.py` | ✓ FOUND |\n",
                "| 4 | Test vector algebra composition | **NOT FOUND** | ✗ MISSING |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Plan Experiments\n",
                "\n",
                "| Experiment | Description | Implementation | Status |\n",
                "|------------|-------------|----------------|--------|\n",
                "| 1 | Portability across contexts | `portability_eval.py` | ✓ FOUND |\n",
                "| 2 | Decoded vocabulary analysis | `vocab_reconstruction.py` | ✓ FOUND |\n",
                "| 3 | Vector algebra composition | **NOT FOUND** | ✗ MISSING |\n",
                "| 4 | Causal mediation across models | `compute_indirect_effect.py` | ✓ FOUND |\n",
                "| 5 | Performance across diverse tasks | `evaluate_function_vector.py` | ✓ FOUND |\n",
                "| 6 | Natural text portability | `natural_text_eval.py` | ✓ FOUND |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Missing Implementation: Vector Algebra Composition\n",
                "\n",
                "The plan describes testing vector algebra composition where:\n",
                "```\n",
                "v*_BD = v_AD + v_BC - v_AC\n",
                "Last-Capital* = Last-Copy + First-Capital - First-Copy\n",
                "```\n",
                "\n",
                "This requires:\n",
                "1. Extracting FVs for First-Copy, Last-Copy, First-Capital tasks\n",
                "2. Computing the algebraic sum to create composed vectors\n",
                "3. Evaluating composed vectors on list-oriented tasks\n",
                "\n",
                "No script implementing this experiment was found in the repository."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### CS2 Verdict: **FAIL**\n",
                "\n",
                "The plan specifies vector algebra composition as a key methodology step and experiment, but no implementation script exists to perform this experiment."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## Summary\n",
                "\n",
                "| Checklist Item | Result |\n",
                "|----------------|--------|\n",
                "| CS1: Results vs Conclusion | **PASS** |\n",
                "| CS2: Plan vs Implementation | **FAIL** |\n",
                "\n",
                "### Details\n",
                "\n",
                "**CS1 (PASS)**: All evaluable conclusions in the documentation match the results originally recorded. The key numerical results for FV performance, natural text portability, vocabulary reconstruction, and vector algebra composition all align between the conclusions drawn and the tabulated experimental results.\n",
                "\n",
                "**CS2 (FAIL)**: The plan specifies 4 methodology steps and 6 experiments. Step 4 (Test vector algebra composition) and Experiment 3 (Vector algebra composition) are missing from the implementation. While the other 5 experiments are fully implemented, there is no script to systematically perform the vector algebra experiments described in the plan and results documented in the paper."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Save the notebook
notebook_path = os.path.join(eval_dir, "self_matching.ipynb")
with open(notebook_path, 'w') as f:
    json.dump(notebook_content, f, indent=2)

print(f"Created: {notebook_path}")

Created: /net/scratch2/smallyan/function_vectors_eval/evaluation/self_matching.ipynb


In [28]:
# Verify the files were created
print("Files in evaluation directory:")
for f in os.listdir(eval_dir):
    full_path = os.path.join(eval_dir, f)
    print(f"  {f} ({os.path.getsize(full_path)} bytes)")

Files in evaluation directory:
  consistency_evaluation.json (1134 bytes)
  self_matching.ipynb (6808 bytes)


## Final Summary

### Files Created:
1. `/net/scratch2/smallyan/function_vectors_eval/evaluation/self_matching.ipynb`
2. `/net/scratch2/smallyan/function_vectors_eval/evaluation/consistency_evaluation.json`

### Results:
| Checklist | Result |
|-----------|--------|
| **CS1: Results vs Conclusion** | **PASS** |
| **CS2: Plan vs Implementation** | **FAIL** |

### CS1 Rationale (PASS):
All evaluable conclusions in the documentation match the results recorded in the paper. Key numerical results for FV performance (90.8% shuffled-label, 57.5% zero-shot for GPT-J), natural text portability (55-68% for Antonym), vocabulary reconstruction (58.1% vs 83.2% for Country-Capital), and vector algebra composition (Last-Country-Capital v*BD=0.60 vs ICL=0.32) all match between conclusions and tabulated results.

### CS2 Rationale (FAIL):
The plan specifies 4 methodology steps and 6 experiments. Step 4 (Test vector algebra composition) is missing from the implementation. While the plan describes experiments combining FVs algebraically (v*BD = vAD + vBC - vAC) to create composed vectors for list-oriented tasks, no implementation script exists to perform this experiment. The other 5 experiments (portability, vocabulary reconstruction, causal mediation, diverse tasks, natural text) are all implemented in the codebase.

In [29]:
# Final verification - read and display the created JSON file
with open(os.path.join(eval_dir, "consistency_evaluation.json"), 'r') as f:
    final_json = json.load(f)

print("Final consistency_evaluation.json:")
print("="*60)
print(json.dumps(final_json, indent=2))

Final consistency_evaluation.json:
{
  "Checklist": {
    "CS1_Results_vs_Conclusion": "PASS",
    "CS2_Plan_vs_Implementation": "FAIL"
  },
  "Rationale": {
    "CS1_Results_vs_Conclusion": "All evaluable conclusions in the documentation match the results recorded in the paper. The main claims about FV performance (90.8% shuffled-label, 57.5% zero-shot for GPT-J), natural text portability (55-68% for Antonym), vocabulary reconstruction (58.1% vs 83.2% for Country-Capital), and vector algebra composition results (Last-Country-Capital v*BD=0.60 vs ICL=0.32) all match between conclusions and tabulated results.",
    "CS2_Plan_vs_Implementation": "The plan specifies 4 methodology steps and 6 experiments. Step 4 (Test vector algebra composition) is missing from the implementation. While the plan describes experiments combining FVs algebraically (v*BD = vAD + vBC - vAC) to create composed vectors for list-oriented tasks, no implementation script exists to perform this experiment. The other 

In [30]:
print("Consistency Evaluation Complete!")
print("="*60)
print(f"\nOutput files saved to: {eval_dir}")
print("\nFiles created:")
print("  1. self_matching.ipynb - Detailed evaluation notebook")
print("  2. consistency_evaluation.json - Summary JSON with checklist results")
print("\nResults Summary:")
print("  CS1 (Results vs Conclusion): PASS")
print("  CS2 (Plan vs Implementation): FAIL")

Consistency Evaluation Complete!

Output files saved to: /net/scratch2/smallyan/function_vectors_eval/evaluation

Files created:
  1. self_matching.ipynb - Detailed evaluation notebook
  2. consistency_evaluation.json - Summary JSON with checklist results

Results Summary:
  CS1 (Results vs Conclusion): PASS
  CS2 (Plan vs Implementation): FAIL
